### ISSUE TITLE
Portal re-work small work tracking issue

### ISSUE THREAD

**Issue by RodgeFu** [merione/public#241]
-  [x] make sure the small percentage will be shown in UI anyway even when it's very small
-  [x] Task List
-  [x] Cache for task query
-  [x] Merge with API refactoring
-  [x] Permission page
-  [x] WorkItemList
-  [x] WorkItemRunList
-  [x] Brief Tab
-  [x] Collapse of the Task List Panel
